{{ if ne .Values.environment "ci" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: default
spec:
  acme:
    server: {{ .Values.issuer.acme.server }}
    email: {{ .Values.issuer.acme.email }}

    privateKeySecretRef:
      name: letsencrypt

    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.issuer.solvers.cloudflare.email }}
          apiTokenSecretRef:
            name: cloudflare-credentials
            key: api-token
{{ end }}
