{{ if ne .Values.environment "ci" }}
{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  {{ if $.Values.namespace -}}
  namespace: {{ $.Values.namespace }}
  {{- end }}
data:
  auth: {{ .secret | b64enc }}
type: Opaque
{{- end }}
{{ end }}
