version: 2

jobs:
  integrationTests:
    docker:
      - image: web3f/ci-commons:v2.4.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh

  publishChart:
    docker:
      - image: web3f/ci-commons:v2.4.8
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - integrationTests:
          filters:
            tags:
              only: /.*/

      - publishChart:
          context: github-bot
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - integrationTests
