environments:
  production:
  ci:
repositories:
  - name: jetstack
    url: https://charts.jetstack.io
releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.7.0
    values:
      - ./config/cert-manager-values.yaml.gotmpl
