environments:
  production:
  ci:
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
releases:
  - name: kube-prometheus-stack
    chart: prometheus-community/kube-prometheus-stack
    version: 27.2.2
    namespace: monitoring
    values:
      - ./config/kube-prometheus-stack-values.yaml.gotmpl
