environments:
  production:
  ci:
repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
releases:
  - name: base-services
    chart: ../charts/base-services
    values:
      - ./config/base-service-values.yaml.gotmpl
  - name: nginx-ingress
    chart: ingress-nginx/ingress-nginx
    version: 4.2.2
    values:
      - ./config/nginx-ingress-values.yaml.gotmpl
