environments:
  production:
  ci:
repositories:
  - name: vmware-tanzu
    url: https://vmware-tanzu.github.io/helm-charts
releases:
  - name: velero
    namespace: velero
    chart: vmware-tanzu/velero
    version: 27.2.2
    values:
      - ./config/velero/velero.yaml.gotmpl
