environment: ci

origin: base

cloudflareApiToken: ""

alertRules:
  create: true
  labels:
    app: w3f

issuer:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: devops@web3.foundation

  solvers:
    cloudflare:
      email: cloudflare@web3.foundation    
