{{ if and (ne .Values.environment "ci") ( .Values.alertRules.create ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: w3f
    origin: {{ .Values.origin }}
  name: general
  {{ if .Values.alertRules.namespace }}
  namespace: {{ .Values.alertRules.namespace }}
  {{ end }}
spec:
  groups:
  - name: general.rules
    rules:
    - alert: TargetDownShort
      annotations:
        message: '{{`{{ $value }}`}}% of the {{`{{ $labels.job }}`}} targets are down.'
      expr: 100 * (count(up == 0) BY (job) / count(up) BY (job)) > 10
      for: 10m
      labels:
        severity: warning
        origin: {{ .Values.origin }}
    - alert: TargetDownLong
      annotations:
        message: '{{`{{ $value }}`}}% of the {{`{{ $labels.job }}`}} targets are down.'
      expr: 100 * (count(up == 0) BY (job) / count(up) BY (job)) > 10
      for: 15m
      labels:
        severity: critical
        origin: {{ .Values.origin }}
{{ end }}
