{{ if and (ne .Values.environment "ci") ( .Values.alertRules.create ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: w3f
    origin: {{ .Values.origin }}
  name: kube-prometheus-stack
  {{ if .Values.alertRules.namespace }}
  namespace: {{ .Values.alertRules.namespace }}
  {{ end }}
spec:
  groups:
  - name: kube-prometheus-stack
    rules:
    - alert: PrometheusOperatorAlertmanagerReconcileErrors
      annotations:
        message: Errors while reconciling Alertmanager in {{`{{ $labels.namespace }}`}} Namespace.
      expr: |
        rate(prometheus_operator_reconcile_errors_total{job="kube-prometheus-stack-operator",controller="alertmanager"}[5m]) > 0.1
      for: 10m
      labels:
        severity: warning
        origin: {{ .Values.origin }}
    - alert: PrometheusOperatorPrometheusReconcileErrors
      annotations:
        message: Errors while reconciling Prometheus in {{`{{ $labels.namespace }}`}} Namespace.
      expr: |
        rate(prometheus_operator_reconcile_errors_total{job="kube-prometheus-stack-operator",controller="prometheus"}[5m]) > 0.1
      for: 10m
      labels:
        severity: warning
        origin: {{ .Values.origin }}
    - alert: PrometheusOperatorNodeLookupErrors
      annotations:
        message: Errors while reconciling Prometheus in {{`{{ $labels.namespace }}`}} Namespace.
      expr: |
        rate(prometheus_operator_node_address_lookup_errors_total{job="kube-prometheus-stack-operator",controller="prometheus"}[5m]) > 0.1
      for: 10m
      labels:
        severity: warning
        origin: {{ .Values.origin }}
{{ end }}
