#https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
  workflow_dispatch:
    secrets:
      PR_PAT:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Run `yarn upgrade`
    - uses: browniebroke/yarn-upgrade-action@v1

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.PR_PAT }}
        branch: update/yarn-upgrade
        title: Run yarn upgrade
        commit-message: "Run yarn upgrade"